networks:
  otel-demo:
    name: otel-demo
    driver: bridge

services:
  jaeger:
    image: jaegertracing/jaeger:2.15.0
    ports:
      - "16686:16686"   # Jaeger UI
    networks:
      - otel-demo

  collector:
    image: otel/opentelemetry-collector:0.144.0
    command: ["--config=/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/otel-collector.yaml:ro
    ports:
      - "4317:4317"     # OTLP gRPC
    depends_on:
      - jaeger
    networks:
      - otel-demo

  ctfd:
    image: ctferio/ctfd:3.8.2-0.9.0
    ports:
      - "8000:8000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "dns://collector:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    depends_on:
      - collector
    networks:
      - otel-demo
